export const discoveryLabels: Record<string, string> = {
  TURK_MUTFAGI: "Türk Mutfağı",
  EV_YEMEKLERI: "Ev Yemekleri",
  SAGLIKLI: "Sağlıklı",
  VEGAN: "Vegan",
  IZGARA: "Izgara",
  SULU_YEMEK: "Sulu Yemek",
  DUNYA_MUTFAGI: "Dünya Mutfağı",
  FIT_MENULER: "Fit Menüler",
  VEJETARYEN: "Vejetaryen",
  PESKETARYEN: "Pesketaryen",
  GLUTENSIZ: "Glutensiz",
  LAKTOZSUZ: "Laktozsuz",
  DUSUK_KALORI: "Düşük Kalori",
  YUKSEK_PROTEIN: "Yüksek Protein",
  DUSUK_KARBONHIDRAT: "Düşük Karbonhidrat",
  KETOJENIK: "Ketojenik",
  PALEO: "Paleo",
  SEKERSIZ: "Şekersiz",
  TUZSUZ: "Tuzsuz",
  DIYABETE_UYGUN: "Diyabete Uygun",
  HELAL: "Helal",
  ORGANIK: "Organik",
  GLUTEN: "Gluten",
  SUT: "Süt",
  YUMURTA: "Yumurta",
  YER_FISTIGI: "Yer Fıstığı",
  SERT_KABUKLU: "Sert Kabuklu",
  SOYA: "Soya",
  BALIK: "Balık",
  KABUKLU_DENIZ_URUNU: "Kabuklu Deniz Ürünü",
  YUMUSAKCA: "Yumuşakça",
  SUSAM: "Susam",
  KEREVIZ: "Kereviz",
  HARDAL: "Hardal",
  ACI_BAKLA: "Acı Bakla",
  KUKURT_DIOKSIT_VE_SULFITLER: "Kükürt Dioksit ve Sülfitler",
};
